# Workflow to install Node and SFDX so we can build a scratch org and deploy to it

name: Deploy To Scratch Org

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch and if something changes in our metadata directory
  push:
    branches: [ master ]
    paths:
      - 'force-app/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'force-app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ GitHub.ref }}
          fetch-depth: 0
        if: GitHub.event.action == 'opened' || GitHub.event.action == 'synchronize' || GitHub.event_name == 'push'
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true

      # Install SFDX using Node
      - name: Install SFDX (Salesforce CLI)
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin run plugins --core
